ManuelHentschel/vscDebugger

- R/prep.R
Close #8 
* `require(pryr, ...)` is replaced with `loadNamespace("pryr")` as `require` tries attach the package and does not stop if not exists while `loadNamespace` only loads the package. All uses of `pryr` in the package is `pryr::` or `pryr:::` so there's no need to attach.
* An `attachList` is used to attach to search path so that the overwritten functions are not directly visible in the global environment.
> Use attach list

- R/prep.R
Quick fix to handle evalRequests with more than 1 expression  (e.g. "a<-1; b<-2") or none (pressing enter with an empty input line).
> Fix handling of evalRequests with more than 1 expression

- R/prep.R
Passes calls to `.vsc.cat` that specify a file to base::cat.
(Partly) fixes https://github.com/ManuelHentschel/vscDebugger/issues/11
> Modify vsc cat

- R/aaaGlobals.R
- R/breakpointManagement.R
- R/customVarInfo.R
- R/debugSource.R
- R/global.R
- R/prep.R
- R/stack.R
- man/getVarListsEntry.Rd
Close #25 
This PR renames `.packageEnv` to `session` to store debug session global variables, which I believe is easier and cleaner to work with.
The `session` object is defined in `global.R`, and `.onLoad` is moved into the file too to indicate everything that happens globally. All access to `session` in other places should be inside a function.
> Use session environment to store debug session globals

- R/customVarInfo.R
This PR uses `str()` to provide object summary and `deparse` to provide representation of scalar value.
Before
After:
> Use cleaner var info

- R/debugSource.R
Changes `.vsc.debugSource` to handle arguments `local`, `envir`, `chdir` in order to better match the behaviour of `base::source` and `base::sys.source`
> Changed .vsc.debugSource arguments to better match base::source, sys.source

- R/prep.R
- man/dot-vsc.cat.Rd
- man/dot-vsc.print.Rd
Adds an argument `skipCalls` to `.vsc.print` and `.vsc.cat`.
Intended usecase is to provide more useful information e.g. from inside logging functions:
``` r
log <- function(...){
.vsc.cat(..., skipCalls=1)
}
log("Log 1")
log("Log 2")
log("Log 3")
```
> Add skipCalls to .vsc.print and .vsc.cat

- R/stack.R
Removes as.list.environment, since it forces the evaluation of promises in the environment (https://github.com/ManuelHentschel/vscDebugger/pull/49#discussion_r436967276).
Instead, a warning is shown.
> Remove as.list.environment()

- R/customVarInfo.R
- R/defaultVarInfo.R
- R/stack.R
Adds a varInfo entry `evaluateName` which can be used to copy variables to clipboard.
> Add evaluateName

- DESCRIPTION
- inst/tinytest/test_buildStack.R
- tests/test.R
- tests/tinytest.R
Relates to #35 
You can find a basic intro to tinytest [here](https://github.com/markvanderloo/tinytest/blob/master/pkg/README.md). 
For now, I only transformed the current (minimal) `.vsc.buildStack` test. You can test it by:
```r
tinytest::build_install_test()
```
This call re-builds the package first, then runs the test.
I do not know the best strategy for writing unit tests for **vscDebugger**. In general, one tests the exported functions of a package (that is, the user-visible part, aka the API of the package). However, here the use case is different, since the exported functions will be called by the R Debugger VSCode extension. So maybe we could distinguish between three (or four?) sets of functions:
1. Functions for communicating with the **R Debugger** extension (exported for …
> Use tinytest instead of testthat

- R/buildStack.R
- R/buildStackHelpers.R
- R/defaultVarInfo.R
- R/defaultVarInfoHelpers.R
- R/setVar.R
Fixes the display of duplicate child variable names, (e.g. `list(b=0, a=1, a=2, a=3)`) by appending the 1-based position to duplicate variable names (e.g. `b`, `a`, `a<3>`, `a<4>`). Changing the variable name is necessary since VS-Code/the DAP does not support child variables with identical names.
Fixes the display of ellipsis arguments.
Changes the info texts printed by setVar.R
> Ellipses and names

- R/helpers.R
Fixes an issue an empty filename was displayed for commands entered in the debug console
> Checks for an empty file path in vsc.print

- R/defaultVarInfo.R
Fixes an issue where the check if a variable is a vector (globally) deletes the attributes of an environment
> Fix deletion of environment attributes

- R/breakpointManagement.R
- R/launch.R
- R/stackHelpers.R
- build.R
Fixes https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/69 ?
The debugger now checks if a file exists before trying to launching a debug session or setting a breakpoint in a file.
> Fix file warnings/errors

- R/defaultVarInfo.R
- R/stackTree.R
Fix #97 
Checks if `VarInfo$childVars()` actually returns the number of chidlren promised by `VarInfo$nChildVars()` and gracefully handles missing entries by showing an info variable with a warning/error message.
Adds VarInfos for `S4 class representation` and `R6`.
> Fix missing childVars

- R/defaultVarInfo.R
Adds a check to avoid deparsing large objects (e.g. vectors with 10,000+ entries) when providing an `evaluateName`.
Uses `object.size` since it's the best proxy for "deparse-cost" I could think of.
If there are variable types with better proxies, we could implement those individually.
> Add max size for deparsed objects

- DESCRIPTION
- R/stackTreeHelpers.R
* Properly handle empty sources. These occurr with functions from packages that were installed from `.tar.gz` etc., but retained (some) source information
* Remove KeepSource from Description -> compiled packages do not contain source references in vsc functions
> Empty sources

- R/communications.R
- R/debugAdapter.R
- R/global.R
- R/launch.R
- R/setVar.R
- d.ts/debugAdapter.d.ts
- d.ts/debugProtocol.d.ts
- d.ts/global.d.ts
Adds support for the new `invalidatedEvent`.
This event is sent after setting a variable to properly display side effects of variable assignments (e.g. assigning a new `dim` to an array affects all other child variables of the array as well).
> Invalidated event

- R/stackTreeHelpers.R
Fixes #122 
There was an error in `normalizePathInWd`, where a function instead of an expression was supplied as `finally` argument in `tryCatch`.
> Fix changed wd in normalizePathInWd()

- R/debugAdapter.R
- R/flow.R
- R/getStack.R
- R/launch.R
This PR repurposes the reverseContinueRequest to exit from the currently executed function without terminating the entire debug session (only sensible when `allowGlobalDebugging = true`).
Since this behaviour is not what the reverseContinueRequest is actually intended for, the feature is disabled by default and can be enabled by setting `options(vsc.repurposeReverseContinue = TRUE)`.
> Repurpose reverseContinueRequest

- R/defaultVarInfo.R
- R/evaluate.R
- d.ts/customVarInfo.d.ts
Adds an entry to VarInfos that specifies how a variable is printed in the debug console.
By default, this is done using the body of the EvaluateResponse, but might can be changed to use e.g. base::print.
Currently, this can be toggled for arrays or all variables using the options `vsc.printEvalResponses` and `vsc.printArrays`.
> Specify how to print variables in debug console

- R/evaluate.R
Fix #164 
Use `.Last.value` instead of `.ans` (by default) and make this variable name configurable.
Set to '' to disable.
> Use .Last.value

- R/debugSource.R
- R/evaluate.R
- R/flow.R
- R/stackTree.R
Addresses https://github.com/ManuelHentschel/vscDebugger/issues/163.
Fixes some constants/flags that would not distinguish internal/external frames correctly when using `.vsc.debugSource` and eval requests.
> Fix frame management

- DESCRIPTION
Fix https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/140
Substitute for https://github.com/ManuelHentschel/vscDebugger/pull/157, https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/130 
Removes svSocket from imports in DESCRIPTION file.
The package needs a modified version of svSocket anyways, that is meant as a temporary workaround and will hopefully be replaced by a proper socket implementation at some point.
> Remove svSocket from IMPORTS
