build.R

https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/7#issuecomment-634619993

Remove unused build to lib

---

R/prep.R

Address https://github.com/ManuelHentschel/vscDebugger/issues/11#issuecomment-636232530.

Fix typo in .vsc.getFileName

---

R/customVarInfo.R
R/stack.R

Improves display of matrices, lists and vertices in the variables window

Improve varinfo

---

R/stack.R
man/dot-vsc.getStack.Rd

Adds an option to force a dummy stack from .vsc.getStack

Force dummy stack

---

R/stack.R
man/dot-vsc.buildStack.Rd
man/dot-vsc.getDummyStack.Rd
man/dot-vsc.getStack.Rd
man/getDummyFrame.Rd
man/getScopes.Rd
man/getStackFrame.Rd

Adds the possibility to include package environments in the scopes of each frame.

Add the possibility to view package scopes

---

R/completion.R

https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/17
Provide completions of symbols from attached packages.

Add completions of symbols from attached packages

---

R/completion.R

Adds completion responses for expression like `package::` and `package:::`

Completion

---

R/completion.R

Add completion of installed packages, language constants, and lazydata.

More completions

---

R/completion.R
R/customVarInfo.R

* Fix for some edge cases in var info
* Add S4 var info
* Add S4 completion

Improve var info

---

R/prep.R
R/stack.R
man/dot-vsc.prepGlobalEnv.Rd

Supporting changes for https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/38

Debug config

---

R/stack.R

This PR handles the issue which was raised [here](https://github.com/ManuelHentschel/vscDebugger/issues/34#issuecomment-640102693) in #34. That is, it gives you the content of `...` without evaluating the arguments.

Handle dots

---

R/customVarInfo.R
R/defaultVarInfo.R
R/stack.R
R/utils.R

Implements internal Attributes suggested in https://github.com/ManuelHentschel/vscDebugger/issues/50#issuecomment-640947413

Custom attributes

---

R/breakpoints.R

Fix warning

---

R/buildStack.R
R/debugAdapter.R
R/global.R
R/helpers.R
R/launch.R
build.R
d.ts/debugProtocolModifications.ts
d.ts/global.d.ts

See https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/51

Clean stdout

---

R/buildStack.R
R/buildStackHelpers.R
R/helpers.R

Fix issue with print and cat

---

.github/workflows/main.yml

Sorry for forgetting to change the name :sweat_smile:

Fix GitHub Actions

---

.github/workflows/main.yml
R/breakpointManagement.R
R/global.R
R/launch.R
R/stackTree.R
README.md
d.ts/debugProtocolModifications.ts
d.ts/global.d.ts

Corresponds to https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/63, https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/56:
> This PR improves the handling and documentation of debugging in packages.

Debug packages

---

R/stackTree.R

Fixes https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/64

Fix frame names

---

.github/workflows/release.yml
d.ts/global.d.ts

Add github action for releases

Add github action for releases

---

R/debugAdapter.R
R/launch.R

Support for fixes to https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/79 and https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/77

Improve handling of terminate/disconnect requests

---

R/flow.R
R/launch.R

Register finalizer to handle quit() in user code

---

.github/workflows/release.yml

Small adjustment to the release workflow

Adjust release task

---

DESCRIPTION

Bump version to 0.4.1

---

.lintr
R/breakpoints.R
R/breakpointsManagement.R
R/launch.R
R/stackTree.R

Fix bugs:
* Properly set breakpoints in exported functions from packages
* Fix column highlighting in active frame

Various bugfixes

---

.github/workflows/pre-release.yml

Publish Pre-Release on pushes to master

Pre-Release

---

.github/workflows/pre-release.yml

Changes the pre-release action to use the same mechanism as is used e.g. in vscode-R.

Modify pre-release action

---

vignettes/breakpoints.Rmd

Addresses https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/126.

Add breakpoint vignette

---

R/communications.R
R/debugSource.R
man/dot-vsc.debugSource.Rd

Improvements to `.vsc.debugSource`, making it possible to set breakpoints while the debugger is stopped on another breakpoint.

Debugsource

---

vignettes/breakpoints.Rmd
vignettes/configuration.Rmd
vignettes/troubleshooting.Rmd
vignettes/vscode-R-Debugger.Rmd

Adds a troubleshooting vignettes and slightly improves the design of other vignettes.

Improve Vignettes

---

.github/workflows/main.yml
DESCRIPTION

Replace non ascii characters in DESCRIPTION

---

vignettes/vscode-R-Debugger.Rmd

Hi Thanks for the geat work!
I think the feature list would be more readable if displayed as a proper numbered list.

Display feature list as proper numbered list

---

.github/workflows/main.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
R/launch.R
R/overwrites.R

Fix load_all overwrite

---

README.md

r-universe install and badge
